/** Single source for compliance copy — show wherever duty amounts appear. */

export const DUTY_ESTIMATE_DISCLAIMER_SHORT =
  "This estimate is generated by Spark & Drive Duty Intelligence using our configurable rules and historical shipment data. It is for planning only — final customs assessment is determined by Ghana Customs at clearance.";

export const DUTY_ESTIMATE_DISCLAIMER_LONG = [
  "Spark & Drive Autos calculates import duty estimates using the Duty Intelligence Engine: configurable Ghana tax rules, freight and insurance matrices, port and clearing charges, live exchange rates, and verified historical imports.",
  "Estimates update immediately when administrators adjust configuration — no external calculators or government websites are required to use this tool.",
  "Final duty, levies, and fees are determined by Ghana Customs when your vehicle is declared and cleared. Use this figure to plan your budget; your clearing agent will confirm the official assessment at the port.",
] as const;

export const DUTY_INTELLIGENCE_SOURCE_NOTE =
  "Powered by Spark & Drive Duty Intelligence — rates, freight, insurance, and port charges are managed in Admin → Duty Intelligence and applied instantly to every estimate.";
