-- Vehicle reserve-with-deposit: extend OrderStatus and add optional pricing / deposit snapshot columns.

ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RESERVED_WITH_DEPOSIT';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'AWAITING_BALANCE';

ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "priceGhs" DECIMAL(14,2);
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "priceUsd" DECIMAL(14,2);
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "priceCny" DECIMAL(14,2);

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "depositAmount" DECIMAL(14,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "remainingBalance" DECIMAL(14,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "orderDepositPercentSnapshot" DECIMAL(5,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "currencyBase" VARCHAR(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "exchangeRateUsed" DECIMAL(18,8);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "reservedAt" TIMESTAMP(3);
